### PR TITLE
Feature/milestone 1

### PR DESCRIPTION
**Pull request by Morrism1**
# ROR_SOCIAL_MEDIA

## What I did:

* I upgraded Rails to 6 from 5 (It was not necessary but I did it) 🤦🏽‍♂️
* I made an ERD for my data

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Maurice Murangwa** 
Good job with your first submission :muscle:  :muscle:
Your Entity relation diagram meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [ ] In your like_dislike table, there is no need for like and dislike columns, the user shouldn't be able to dislike a comment, and the like exists if the record exists in the database.
- [ ] Add the Entity relation diagram in your README file.
- [ ] Next time don't repeat the same commit message many times.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by Morrism1** [comment]
> ### Status: Changes Required ♻️
> **Hello Maurice Murangwa**
> Good job with your first submission 💪 💪
> Your Entity relation diagram meets most of the requirements 👏 👏 👏
> There are just a few details to improve before you can go ahead:
> 
> * [ ]  In your like_dislike table, there is no need for like and dislike columns, the user shouldn't be able to dislike a comment, and the like exists if the record exists in the database.
> * [ ]  Add the Entity relation diagram in your README file.
> * [ ]  Next time don't repeat the same commit message many times.
> 
> Please request another review once you are ready! 👍
> 
> Happy coding ☺️
> 
> Oscar Andrés Russi Porras

Thanks, @andresporras3423. The Commit messages became a bit of order because I challenged myself to upgrade Rails and there were a lot of conflicts and resolved them with the same message. That was bad. Noted.

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

### Hello Team 👋 

Great job on implementing the Entity Relationship Diagram, I can't wait to see your finished app. Good luck with your next milestone.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Comment by Morrism1** [comment]
> # Status: PROJECT APPROVED 🎉 🚀
> ### Hello Team 👋
> Great job on implementing the Entity Relationship Diagram, I can't wait to see your finished app. Good luck with your next milestone.
> 
> ### Cheers and Happy coding! 💻 👏
> (Feel free to contact me on slack(@acushla), if you have any additional question)
> Uduak Essien
> [Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

Thanks @acushlakoncept 🙌

**Pull request merged**
